marcobambini/gravity

- docs/getting-started.html
Edited `Getting Started` page:
* Added visible sections
* Added supported code editors
* Added some tips
> Edited "Getting Started" page

- src/runtime/gravity_core.c
- test/list_contains.gravity
Test: https://github.com/leonardosnt/gravity/blob/f9f38f1c3065106d1506bef0f2d7bd7e2e880252/test/list_contains.gravity
> Implement List.contains

- src/utils/gravity_utils.c
Windows build - Use wide char path functions and fix for returning stack variable
In `directory_read` in `gravity_utils.c`, for Windows it was returning a local variable which caused the value used in `test_folder` to be undefined.
Also `directory_init` wasn't using the wide char methods.
`unittest.exe test` runs successfully now:
```
==============================================
Total Tests: 76
Total Successes: 76
Total Failures: 0
Result: 100.00 %
Time: 836.3863 ms
==============================================
```
> Windows build - Use wide char path functions and fix for returning stack variable

- docs/lists.html
I noticed that recently a join method was pushed, but no documentation on its usage.
> Added the list join method to the docs

- docs/lists.html
There was no documentation for the list contains method. To make it easier to find, I added a section for it in the lists.html doc
> Added a section in lists.html for the contains method

- CONTRIBUTING.md
Just a suggestion. Maybe part of the contribution guidelines for editing or adding new functionality should be to add documentation about the change to the docs?
That way there won't be information missing from the docs about newer functionality.
> Added a section to CONTRIBUTING.md about adding to docs

- docs/system.html
Added some documentation for the new System.exit() call.
> Added System.exit() to the docs

- src/runtime/gravity_core.c
- test/bitwise_on_bool.gravity
Ref: #81 
This excludes the `<<` and `>>` operations, since that would kind of go against what a bool is in my opinion.
> Added support for bitwise operations on booleans

- TODO.md
- docs/syntax.html
Also, removed that task from the TODO list
I stuck it into the syntax file, but perhaps you want it somewhere else? Maybe its own import.html file or something?
> Added documentation for the import statement.

- docs/types.html
- src/runtime/gravity_core.c
PR also updates the docs to reflect the method name change from `string_repeat()` to `repeat()
> Made the changes requested by @InusualZ in #97

- docs/system.html
- src/runtime/gravity_core.c
- test/random_int.gravity
- test/random_int_error_args_not_ints.gravity
- test/random_int_error_no_args.gravity
- test/random_int_multiple_attempts.gravity
```swift
System.random(-5, 10) // returns a random integer between -5 and 10 inclusively
```
> Added a random() method for System

- docs/system.html
- docs/types.html
- src/runtime/gravity_core.c
- test/random_int.gravity
- test/random_int_error_args_not_ints.gravity
- test/random_int_error_no_args.gravity
- test/random_int_multiple_attempts.gravity
I moved the System.random() method to Int.random() as discussed in #106.
Have not done any floats or bools etc. Also, the rand() function is still being used as I was still not able to get that arc4random function working.
> Changed System.random() to Int.random()

- docs/types.html
- src/runtime/gravity_core.c
- test/string/complex_split.gravity
- test/string/no-split.gravity
- test/string/split.gravity
- test/string/split_runtime_error.gravity
Acts as a reverse to the List.join()
Only takes one (string) argument.
> Added a String.split() method.

- .gitignore
- docs/types.html
- src/optionals/gravity_math.c
- src/runtime/gravity_core.c
- test/unittest/math/cbrt.gravity
- test/unittest/math/gcf.gravity
- test/unittest/math/lcm.gravity
- test/unittest/math/log.gravity
- test/unittest/radian_degree_conversion.gravity
I have added a cube root function (cbrt) along with a gcf and lcm, and in addition to the log function that already existed, I added a log10 for base 10 logs, and a logx for variable based logs (ie, "Math.logx(2,4)" is a base 2 log of 4 and equates to 2).
I also fixed the Math.random() function as it always resulted in a 0 (the random value just needed to be casted to a float).
I also added a degrees and radians property to the Int and Float types so that you can say "30.radians" to convert 30 degrees into radians for example.
And finally, the current gitignore was ignoring the "test/unittest" folder because of the line "unittest" that was meant to block the unittest executable. So I added an exception to the gitignore for that.
> Added some functionality to Math class

- docs/api.html
- docs/classes.html
- docs/closures.html
- docs/contributing.html
- docs/control-flow.html
- docs/enum.html
- docs/fibers.html
- docs/functions.html
- docs/getting-started.html
- docs/index.html
- docs/lists.html
- docs/loops.html
- docs/maps.html
- docs/math.html
- docs/operators.html
- docs/syntax.html
- docs/system.html
- docs/types.html
- docs/unit-test.html
Noticed that there wasn't a documentation file for the new Math class, so I went ahead and added one quickly.
> Added a Math class docs file

- docs/math.html
This is the updated math docs after my additions to the math class were just merged.
> Updated math doc after the new math functions were merged

- docs/loops.html
- src/runtime/gravity_core.c
- test/unittest/string/for_in.gravity
- test/unittest/string/loop.gravity
This allows a user to loop through a string character by character using
the for-in loop, or the loop() method.
> Added a string iterator and loop function.

- docs/api.html
- docs/classes.html
- docs/enum.html
- docs/lists.html
- docs/loops.html
- docs/syntax.html
- docs/system.html
- docs/types.html
While reading through the docs I saw a few spelling mistakes and other things which (I think) are not correct.
I'm not a native speaker but I hope everything is alright.
> Doc spelling fixes

- src/runtime/gravity_core.c
- test/unittest/list_reverse.gravity
- test/unittest/list_reversed.gravity
- test/unittest/list_sort.gravity
- test/unittest/list_sorted.gravity
This branch should have fixed the integer underflow error that had happened due to my erroneous use of uint32_t. I've also added a few more test cases to cover what caused the bugs and some common cases (sorting/reversing an empty list, etc.). Hopefully it's all set now
> Sort and reverse fixed

- src/compiler/gravity_parser.c
Fixed a typo in the parser error message
> Fixed a typo in parse error message

- src/runtime/gravity_core.c
- test/unittest/list_filter.gravity
- test/unittest/list_map.gravity
- test/unittest/list_reduce.gravity
This is my implementation of map, filter, and reduce, as originally suggested by @hallzy and outlined in #194 . I've added unit tests that I believe show that the methods work as expected. There are some potential optimizations to be made. For example, right now filter is optimized for speed, not memory. If memory is an issue, we can try to make sure that we only allocate the right size for the filtered array (right now it will almost always be oversized).
> Map reduce filter

- docs/lists.html
I noticed that while there was a map, filter, and reduce method for the lists class, there was no documentation for it in the docs, so I thought I would add it.
> Added documentation for the map, filter, and reduce methods for lists

- src/cli/gravity.c
This shuffles help output in order to be easier for newcomers to grasp.
> Format help output

- docs/class.md
Found that documentation surrounding class inheritance was missing. So, here you go!
> Added class inheritance documentation

- src/compiler/gravity_ast.h
- src/compiler/gravity_codegen.c
- src/compiler/gravity_semacheck2.c
- test/unittest/flow_switch.gravity
- test/unittest/ternary_operator.gravity
This makes ternary operator and switch statement work.
> Added ternary expr and switch stmt codegen

- docs/class.md
Include documentation about Class constructors and destructors as well as a code example.
Code example tested and working using latest version of master.
> Add constructor and destructor to class documentation

- src/compiler/gravity_ast.h
- src/compiler/gravity_compiler.h
- src/compiler/gravity_ircode.h
- src/compiler/gravity_lexer.h
- src/compiler/gravity_parser.h
- src/compiler/gravity_symboltable.h
- src/compiler/gravity_token.h
- src/runtime/gravity_core.h
- src/runtime/gravity_vm.h
- src/shared/gravity_delegate.h
- src/shared/gravity_hash.h
- src/shared/gravity_memory.h
- src/shared/gravity_value.h
- src/utils/gravity_json.h
- src/utils/gravity_utils.h
Sorting functions inside headerfiles to find them more easily.
> sorting headerfiles

- .travis.yml
- test/unittest/run_all.sh
Add unit test run to the CI to ensure there are no regressions introduced
> Add unit test run to the CI
