marcobambini/gravity

Makefile, src/compiler/gravity_token.h, src/shared/gravity_array.h
just added header and a linker math library to fix make compile errors
after these changes was able to successfully compile on 
64 bit  Ubuntu 16.04 
gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
=> was failing to compile linux - error: unknown type name ‘uint16_t’

docs/classes.html, docs/enum.html, docs/functions.html, docs/lists.html, docs/loops.html, docs/maps.html, docs/syntax.html, docs/unit-test.html
Just a few grammatical fixes I made in the docs.
As for the "indices" vs "indexes", while both words are correct plural forms of index, it is probably best to keep it consistent, so I just changed two instances of "indexes" to "indices"
=> Some Grammar Fixes in the Docs

.gitignore
These generated executables probably should be in the gitignore.
Up to you though.
=> Added "gravity" and "unittest" executables to gitignore

src/utils/gravity_utils.h
Otherwise it does not compile on WIN32.
=> _int64 does not exist but __int64 on WIN32

syntax_highlighting/vim/ftdetect/gravity.vim, syntax_highlighting/vim/indent/gravity.vim, syntax_highlighting/vim/syntax/gravity.vim
Reference #26 and #23 for syntax highlighting.
This is copied from
* https://github.com/keith/swift.vim
The original author requires that copyright notice to be in his work
when used elsewhere.
Also, this is unmodified (except for substitutions of "swift" with "gravity",
so it is actually a highlighting for swift.
It works well for gravity currently though, and we can change it as
needed.
=> Added vim syntax highlighting.

Makefile, src/utils/gravity_utils.c, src/utils/gravity_utils.h
Building with:
`mingw32-make CC=gcc`
This will successfully build both `gravity.exe` and `unittest.exe`.
I have tested gravity.exe with examples on https://marcobambini.github.io/gravity/syntax.html and it works OK. Linux build is unbroken (tested on Windows 10 bash).
This has uncovered a bug with the `unittest` project where there is a problem with `directory_read` and `FindNextFile` on win32 and is not finding files, but thats for another issue/PR.
=> Windows build - Fix file read/write and windows includes

Makefile, src/compiler/gravity_ast.c, src/compiler/gravity_codegen.c, src/compiler/gravity_ircode.c, src/runtime/gravity_core.c, src/shared/gravity_hash.c, src/shared/gravity_value.c, src/utils/gravity_json.c
This should remove all the warnings that get produced from make.
All tests pass for me with this change.
I forgot to disable the part of my text editor that removes trailing whitespace, so there are a lot of those changes. If you would prefer to not have the whitespace removed in these commits, let me know and I will go back through and just make the actual changes (since the whitespace changes account for a lot of modifications)
The `-fgnu89-inline` flag in the Makefile tells GCC to use the traditional GNU semantics for inline functions when in C99 mode, thus eliminating the warnings produced by the inline functions
=> Remove warnings

docs/syntax.html
It seems there are some indentation errors at "Gravity: Syntax" > "Blocks and Scope"
see: https://marcobambini.github.io/gravity/syntax.html
1 tab is used in other code blocks.
=> Fix indentation in syntax.html

docs/stylesheets/styles.css
Tabsize is currently way too wide, making code examples look kinda odd. This one-liner PR fix that.
Example:
=> Making tab-size smaller in highlighted code

docs/operators.html, docs/syntax.html
since "isa" is not longer used, I thought it be best to change the docs to reflect this to avoid confusion
=> Changed isa to is in docs

docs/lists.html
I noticed that "treat" was spelled wrong in the lists.html doc.
=> Fixed a typo in lists.html for the push/pop section

CONTRIBUTORS, Makefile, src/compiler/gravity_compiler.h, src/runtime/gravity_vm.h, src/shared/gravity_value.h
Added ```extern "C" {``` to fix include issues with C++ builds. Also added ```make lib``` to build a shared object that can be linked with C++ programs.
=> Added C++ include support and created Makefile command to build a shared object.

CONTRIBUTING.md
Without the space between the `####` and the heading, github doesn't
render the heading properly.
=> Fixed a Spelling mistake and MD syntax

src/compiler/gravity_ircode.c
```bash
src/compiler/gravity_ircode.c: In function ‘ircode_dump’:
src/compiler/gravity_ircode.c:290:18: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 5 has type ‘int64_t {aka long int}’ [-Wformat=]
```
Went to rebuild gravity with the latest changes and received this warning.
Looks to be the same as one of the warnings I had earlier: https://github.com/marcobambini/gravity/pull/39#issuecomment-284965685
=> Resolves a compilation warning regard %lld

docs/getting-started.html
Adds my [language-gravity](https://github.com/Tribex/atom-language-gravity) Atom package and @hallzy's [vim plugin](https://github.com/hallzy/gravity.vim) to the list of third-party editor plugins on the getting started page in the docs.
Also, I made a couple minor tweaks to the grammar in the getting started page because I can't avoid being a grammar nazi.
Great work on Gravity!
=> [Docs] [Getting Started] Add Atom and vim language package links, minor grammar tweaks.

docs/syntax.html
Not sure if you want it, but I thought I would add a snippet about the "#!" shebang in the syntax docs... I thought it would be worth having in the docs just because people may assume that because gravity has c-style comments that the classic "#!" shebang would not work. So explicitly stating that it does actually work might be useful for those people.
=> Added info about the shebang in syntax.html

docs/types.html, src/runtime/gravity_core.c, test/string/count_method.gravity, test/string/index_method.gravity, test/string/index_method_error.gravity, test/string/index_method_notfound.gravity, test/string/loadat.gravity, test/string/loadat_error.gravity, test/string/storeat.gravity, test/string/storeat_error.gravity, test/string/string_repeat_method.gravity, test/string/string_repeat_method_error.gravity, test/string/upper_lower_method.gravity
Before you look at any of this, I just want to point out that the `test/string/storeat.gravity` fails, but I have checked it a few times and I don't see why it would fail. I checked the output of what I returned and it all looks good. So I am not sure if there is a bug in the unittest, or if I have missed something, but the result that I get from the test is what I expect
Since I don't have the time to go and finish up the date class right now, I thought I would contribute some string methods instead.
This will allow you to edit strings using the `[ ]`... ie, now `"Hello"[0]` will return a `H`... setting also works, so:
```swift
var s = "rain"
s[1] = "ipe" // now s is "ripe"
```
negative indices still work as well.
Also has an index() method that returns the index of the string that the …
=> String methods

src/runtime/gravity_core.c, test/string/upper_lower_method.gravity
I discovered while looking over my code that the upper() and lower() methods themselves actually modify the base string. For example:
```swift
var str = "HeLLo"
str.Upper()
System.print(str) // prints out "HELLO"
```
This was not my intention when I made these methods. My intention was:
```swift
var str = "HeLLo"
var ret = str.Upper()
System.print(str) // prints out "HeLLo"
System.print(ret) // prints out "HELLO"
```
so I have added to the testcases, and modified the code to resolve that issue. I apologize for this error.
=> String.upper() and .lower() shouldn't modify the string directly

src/compiler/gravity_ircode.c
I got one of these warnings again when I compile gravity.
=> Resolved a compilation warning regardding %lld/ %ld

src/utils/gravity_json.c
I was looking at the compiler's output and I saw something like this:
```
"nlocal" : 0,
"ntemp" : 1,
"nup" : 0,
"purity" : 0.500000,
"bytecode" : "200400003C040001C40400023C040003",
"pool" : [
{
"type" : "class",
"identifier" : "Vector",
"nivar" : 3,
"init" : {
"type" : "function",
"identifier" : "init",
```
This fixes the indentation of that curly brace and makes `json_begin_array` robust against passing a key when not in an object like `json_begin_object`.
=> Fix JSON pretty printing when not inside an object and a key is given.

src/cli/unittest.c
This will help with certain automations that look for error codes to
determine what happens.
For example, running `git bisect` or an interactive rebase using exec,
or any other type of automated testing or building that users use.
With the new return codes commands like bisect will understand that the test has failed
=> Have the unittests return an error of a test fails

src/cli/gravity.c
Before
```
leonardosnt:~/workspace (master) $ ./gravity a.gravity
Error loading file a.gravityleonardosnt:~/workspace (master) $ 
```
After
```
leonardosnt:~/workspace (master) $ ./gravity a.gravity
Error loading file a.gravity
leonardosnt:~/workspace (master) $ 
```
=> add missing \n

docs/types.html, src/runtime/gravity_core.c, test/string/loadat.gravity, test/string/loadat_error.gravity
added a substring method that takes either 1 or 2 arguments.
if one argument is provided, it takes the substring defined by that index of the string, to the end of the string, otherwise it is the string defined by two given indices.
For example:
```swift
var str = "Hello, World!"
return str.substr(7, 11) // "World"... or str.substr(7, -2)
```
Not sure if someone else has a better name for it, but I am open to suggestions if substr() is not appealing.
It also seems that some languages specify the ending index of the character after the last character you want, while this stops the substring at the character you specify...
For instance, in JS that substring command I gave above would return "Worl" instead of "World".
I have also seen some languages take the substring length as the second …
=> Added a String.substr() method

README.md
Looking at the Markdown, it looked like the intention was to have some of the bullets indented more than the others, but that wasn't being reflected in the markdown on the main page, so I indented them more to make them render as sub bullets.
Assuming that this actually was the intention.
=> Indented bullets under opening an issue and PR in README

Makefile, api/Makefile
As it says, in preparation for adding gravity to the official OpenBSD packages repository.
=> Build on OpenBSD.

src/cli/gravity.c
It is useful to pass gravity's output to other command by pipe like `gravity -q script.gravity | wc -l`.
=> Added -q option to cli to be quiet result and execution time output

src/runtime/gravity_core.c
I was getting a compilation warning with this particular line of code. Changing to `%ld` from `%lld` removes the warning for me.
=> Resolved a compilation warning about %lld

docs/math.html, src/optionals/gravity_math.c, test/unittest/math/xrt.gravity
I thought that maybe having a variable root would be useful:
```swift
Math.xrt(4, 16) // This gives the quartic root of 16 = 2
```
the name came from the `sqrt` and `cbrt`, but I am not sure if the name is clear. I am open to changing it.
=> Added a variable radical method

src/runtime/gravity_core.c, test/unittest/list_reverse.gravity, test/unittest/list_reversed.gravity, test/unittest/list_sort.gravity, test/unittest/list_sorted.gravity
This idea was originally floated in issue #104. Four list class methods have been added here--reverse(), reversed(), sort(), and sorted(). Sort() and sorted() both take a "predicate" argument, which is a function (closure) that takes two arguments and returns a "truthy" value. The sort functions use an implementation of quicksort, though Timsort was also suggested as a possibility.
Unittests have been added to make sure that reverse() and sort() modify the original list, while reversed() and sorted() return a new list and leave the original unmodified.
I'd appreciate any feedback!
=> Built in sort and reverse

Makefile
Some packaging tools (e.g. OpenBSD ports) predefine CC, since our default compiler is clang, not gcc. This allows systems that don't have CC defined to use gcc, and those that do use their preselected compiler. As-is, your invocation of CC=gcc clobbers any predefined CC, and this breaks the OpenBSD ports build without additional patching on our end.
=> Reduce CC = to CC ?= in Makefile

.gitignore
Without those lines, the unittest executable shows up in a git status as
untracked as opposed to be ignored.
These lines used to be in the gitignore but were removed in d7b73ef19dc351f06b3dbd5960766728e38a1fd3#diff-a084b794bc0759e7a6b77810e01874f2 though I am not sure why. If there was a reason for it can someone let me know.
=> Added unittest and !test/unittest to .gitignore

docs/types.html, src/runtime/gravity_core.c, test/unittest/string/split_string_to_list.gravity
Previously, this was an undefined case that would result in an infinite
loop. Now it acts the same as in JavaScript, and it returns a list
where every element is 1 character of the string.
This is useful for applying list methods to strings such as map, reduce,
filter, contains etc
=> split('') will now split a string at every character.

src/cli/gravity.c
WideCharToMultiByte outputs to a `const` buffer.
=> Output buffer should not be const.

src/runtime/gravity_vm.c
It only took Clang into consideration.
=> Supress division by zero warning in GCC.

src/cli/gravity.c, src/utils/gravity_utils.c, src/utils/gravity_utils.h
On Windows, `directory_read()` utility returns the address of a fixed size array from a local structure. The fix is quite hackish but does the job.
=> Function returns address of local variable fix.

CMakeLists.txt
Updated CMakeLists.txt to support the following targets:
- **gravity** cli
- **gravityapi** shared lib (.dylib, .dll, .so)
- **gravityapi_s** static lib (.lib, .a)
Tested:
- Windows (VC2019, MinGW64)
- Ubuntu (gcc)
- MacOSX (xcode)
#295 - builds with MinGW
`md build && cd build`
`cmake -G "MinGW Makefiles" ..`
`cmake --build .`
=> Updated CMakeLists.txt to support multiple targets

src/shared/gravity_config.h, src/shared/gravity_macros.h, src/shared/gravity_value.c, src/shared/gravity_value.h
Added `GRAVITY_USE_HIDDEN_INITIALIZERS ` define in gravity_config.h to solve the issue of using Gravity in pre C++20 projects.
Added `gravity_value_from_XXX` functions that implement the `VALUE_FROM_XXX` macros
Reference: #300 Public macros with C++ compatibility
=> GRAVITY_USE_HIDDEN_INITIALIZERS to hide public facing designated initializers when using C++

src/cli/gravity.c
Running `gravity -t` on Windows would fail to find any files to test. Even when the specified path is correct.
`directory_read` uses `FindNextFileA` on Windows which already returns a multi-byte.
`unittest_scan` was attempting to convert a wide char to char.
Tested on Windows with (MSVC, MinGW)
=> Fixed issue in running unit tests on Windows

docs/string.md
I'm not familiar with swift. However, I discovered the string interpolation in the unit tests.  Added a brief comment about it in the docs.
*Related:* It looks like Gravity scripts and strings are **UTF8**.  I was able to verify when reading a Gravity string from C.
Should there be a comment somewhere indicating they are UTF8?
=> added example on inline string formatting

CMakeLists.txt
CMakeLists.txt did not define `BUILD_GRAVITY_API` for the shared library.  This caused exporting to not work on Win32.
=> fixed CMake Win32 shared library export

src/utils/gravity_utils.c
size_t is unsigned, so comparison against -1 effectively causes undefined behavior
Found via UBSan (Undefined Behavior Sanitizer) in Clang 11
Fixes:
```
src/utils/gravity_utils.c:150:19: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'unsigned long' changed the value to 18446744073709551615 (64-bit, unsigned)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/utils/gravity_utils.c:150:19 in
```
=> fix size_t comparison of negative in file_read()

src/utils/gravity_utils.c
Marco, you probably recall that I'm not a strong C programmer, so take this fix with a grain of salt. I used https://wiki.sei.cmu.edu/confluence/display/c/STR34-C.+Cast+characters+to+unsigned+char+before+converting+to+larger+integer+sizes as my guide for suggesting a fix for this one. Please let me know if this is not appropriate or does not solve the problem in the right way.
Found via UBSan (Undefined Behavior Sanitizer) in Clang 11
Fixes:
```
src/utils/gravity_utils.c:473:23: runtime error: implicit conversion from type 'char' of value -27 (8-bit, signed) to type 'unsigned char' changed the value to 229 (8-bit, unsigned)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/utils/gravity_utils.c:473:23 in
```
=> fix signed char to unsigned char conversion in utf8_charbytes()

src/utils/gravity_utils.c
This resolves the runtime errors, but I'm quite unsure if this is the proper way to resolve the issue. I compared to the Wren source, only to notice the variable types have been changed, which may result in this type mismatch?
Found via UBSan (Undefined Behavior Sanitizer) in Clang 11
Input file:
[utf8_encode_char.txt](https://github.com/marcobambini/gravity/files/5436642/utf8_encode_char.txt)
Fixes:
```
src/utils/gravity_utils.c:518:18: runtime error: implicit conversion from type 'unsigned int' of value 170 (32-bit, unsigned) to type 'char' changed the value to -86 (8-bit, signed)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/utils/gravity_utils.c:518:18 in
```
=> fix uint32_t to char conversions in utf8_encode()

CMakeLists.txt, src/CMakeLists.txt, src/cli/CMakeLists.txt
Having the CLI CMake file and Libraries CMake file in different directories allows third-party applications to reference the library file directly, without having to compile the executable...
``` cmake
add_subdirectory(vendor/gravity/src)
target_link_libraries(myproject gravityapi)
```
This is the recommended pattern for [Modern CMake](https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html).
@foobit Mind a review? It's working for me. Can reference just the source directory, and still build the executable with cmake no problem.
=> cmake: Split up the CLI and Library CMake definitions

src/utils/gravity_utils.c, src/utils/gravity_utils.h
This change removes `readline()` from `gravity_utils` because `getline()` isn't available on some platforms, causing fatal errors during compilation of `gravityapi`. Since REPL isn't implemented yet, `readline()` isn't used anywhere anyway.
Would be optimal to implement it as part of `gravity.c` when we get REPL in.
=> Remove readline() from gravity utils

src/utils/gravity_utils.c
There is a small typo in src/utils/gravity_utils.c.
Should read `sanitizer` rather than `sanityzer`.
=> docs: fix simple typo, sanityzer -> sanitizer

src/runtime/gravity_core.c, src/shared/gravity_opcodes.h
Solves issue #21 adding a simple method for getting input from the user, even without a REPL.
system_input uses fgets instead of scanf and should be safe for buffer overflows.
The buffer size for now is 1024 because this seemed to be the most used buffer size in the repo.
=> Add System.input() for input from stdin

docs/env.md, src/cli/gravity.c, src/optionals/gravity_opt_env.c, src/optionals/gravity_opt_env.h
This pr addresses #113 and #235 adding a way to pass arguments to the script. Unlike the approach suggested by IngwiePhoenix in #235 here the arguments are not passed to the main function but are registered as properties of the ENV class. I am unsure if the System class is more appropriate than the ENV class, but this should be chosen by the maintainer/community.
Pros of this approach:
- Arguments are accessible from anywhere in the program and not only in the main function
- Arguments are not passed directly to the vm / run function
- Passing CLI arguments is optional and require a separate register function 
Cons:
- Arguments are tight to an optional class
- To register the arguments you have to include the gravity_opt_env.h header
Possible improvements:
- Unify argc and argv to a …
=> Add a way to pass command line arguments

api/exec_c.c, api/exec_gravity.c
The last boolean argument was missing in api examples.
=> Fix api example

src/optionals/gravity_opt_math.c
This simple pull request fixes an implicit conversion warning on Clang 12.0 :
```
src/optionals/gravity_opt_math.c:908:45: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
```
=> Clang: Fixed implicit conversion from long to double

src/utils/gravity_utils.c
fix line ending causing fsize != fsize2 in gravity_utils.d/file_read() due to not reading in binary mode.
On Windows when opening a file in text mode `\r` is ignored (and not read) after each `\n`. This causes files never to be loaded and giving an uninformative error just being: "`Error reading file [...]`". `\r`s are ignored by the compiler anyway.
=> fix read size different from fs-info file-size due to line-ending

src/shared/gravity_hash.c, src/shared/gravity_hash.h, src/shared/gravity_value.c, src/shared/gravity_value.h
see #368 for more details.
In short: hash functions are expected to be in `g*_hash.h` When dynamically linking this makes more sense.
=> move hash functionality

Makefile, src/CMakeLists.txt
Hello --
The BSDs are building with a -D_WITH_GETLINE switch that appears unreferenced in the code itself.
Additionally, there's no technical reason why not to build the shared library (if wanted) either, so make it available.
Thanks!
=> Build shared object on BSDs; remove unneeded WITH_GETLINE.

Makefile
This PR fixes an issue in the Makefile. Specifically, previously, any modifications of files like src/optionals/*.h would not trigger a rebuild of  src/optionals/*.o. The PR fixes this by including them as additional dependencies.
=> fix missing dependecies in Makefile
